### ISSUE TITLE
Repl.it is blocked here 

### ISSUE THREAD

**Issue by Hacker1254** [Caalek/ytmp3#1]
http://ytmp3.calek.repl.co/ is blocked so can you make it all run locally *im trying to find a way to get mp3 files for my downloader , Check it out at https://github.com/Hacker1254/Youtube-Downloader-Unblocked and https://bit.ly/3s9u5Pu

**Comment by Caalek** [comment]
You can always download the [backend code](https://github.com/Caalek/ytmp3-backend) and run it locally if you want, but then you would have to find another key-value databse solution, as https://ytmp3.calek.repl.co/ used the Repl.it's key-value database. If you're just looking for a way to get mp3 files from YouTube, check out [youtube_dl](https://github.com/ytdl-org/youtube-dl). It's the program i used in my API and it has Python bindings, so you could write a Python API with it yourself.

**Comment by Hacker1254** [comment]
ok thanks
